### ISSUE TITLE
exporter: UnboundLocalError: local variable 'img_tmp_path' referenced before assignment

### ISSUE THREAD

**Issue by slapin** [okamstudio/godot#1332]
Was hit by these passing by:
```
NAME: Lamp
NAME: Camera
NODE TYPE: ARMATURE NAME: girl2
NODE TYPE: MESH NAME: girl2-adult_female_genitalia
Type: <class 'int'>
IDX: 0/1
Traceback (most recent call last):
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/__init__.py", line 179, in execute
    return export_dae.save(self, context, **keywords)
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1646, in save
    exp.export()
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1571, in export
    self.export_scene()
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1269, in export_scene
    self.export_node(obj,2)
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1223, in export_node
    self.export_node(x,il)
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 1212, in export_node
    self.export_mesh_node(node,il)
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 907, in export_mesh_node
    meshdata = self.export_mesh(node,armature)
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 544, in export_mesh
    materials[f.material_index]=self.export_material( mat,mesh.show_double_sided )
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 256, in export_material
    imgid = self.export_image(ts.texture.image)
  File "/home/slapin/blender-2.73-linux-glibc211-x86_64/2.73/scripts/addons/io_scene_dae/export_dae.py", line 215, in export_image
    if img_tmp_path.endswith((".bmp",".rgb",".png",".jpeg",".jpg",".jp2",".tga",".cin",".dpx",".exr",".hdr",".tif")):
UnboundLocalError: local variable 'img_tmp_path' referenced before assignment
```

**Comment by slapin** [comment]
That code looks weird - seems like copy-paste error

**Comment by beniwtv** [comment]
Yep, had the same issue, was reported in #1302

**Comment by slapin** [comment]
This one is fixed by PR1336, see
https://github.com/okamstudio/godot/pull/1336
