### ISSUE TITLE
Error when running app exported using OpenJDK 8.

### ISSUE THREAD

**Issue by zackp30** [okamstudio/godot#2014]
I'm aware OpenJDK 8 isn't exactly "supported", but I thought it might be helpful to file a bug for when it is:

```
D/GODOT   ( 1951): ** GODOT ACTIVITY CREATED HERE ***
D/AndroidRuntime( 1951): Shutting down VM
E/AndroidRuntime( 1951): FATAL EXCEPTION: main
E/AndroidRuntime( 1951): Process: org.godotengine.gametest, PID: 1951
E/AndroidRuntime( 1951): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.godotengine.ga
metest-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libgodot_android.so"
E/AndroidRuntime( 1951):        at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime( 1951):        at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 1951):        at com.android.godot.GodotLib.<clinit>(GodotLib.java:39)
E/AndroidRuntime( 1951):        at com.android.godot.Godot.initializeGodot(Godot.java:350)
E/AndroidRuntime( 1951):        at com.android.godot.Godot.onCreate(Godot.java:513)
E/AndroidRuntime( 1951):        at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 1951):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 1951):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime( 1951):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
E/AndroidRuntime( 1951):        at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 1951):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 1951):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1951):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 1951):        at android.app.ActivityThread.main(ActivityThread.java:5257)
E/AndroidRuntime( 1951):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1951):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1951):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 1951):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager( 1211):   Force finishing activity 1 org.godotengine.gametest/com.android.godot.Godot
I/ActivityManager( 1211): Config changes=480 {1.0 310mcc260mnc en_US ?layoutDir sw320dp w320dp h544dp 240dpi nrml long port finger qwerty/
v/v -nav/h s.9}
```

When taking a look inside the APK:

```
$ tree
.
├── AndroidManifest.xml
├── assets
│   ├── button.gdc
│   ├── _cl_
│   ├── engine.cfb
│   ├── fig.jpg
│   ├── icon.png
│   ├── icon.png.flags
│   ├── main.gdc
│   ├── main.res
│   └── main.scn
├── classes.dex
├── META-INF
│   ├── ANDROIDD.RSA
│   ├── ANDROIDD.SF
│   └── MANIFEST.MF
├── res
│   ├── color
│   │   ├── common_signin_btn_text_dark.xml
│   │   └── common_signin_btn_text_light.xml
│   ├── drawable
│   │   ├── common_signin_btn_icon_dark.xml
│   │   ├── common_signin_btn_icon_light.xml
│   │   ├── common_signin_btn_text_dark.xml
│   │   ├── common_signin_btn_text_light.xml
│   │   └── icon.png
│   ├── drawable-hdpi
│   │   ├── common_signin_btn_icon_disabled_dark.9.png
│   │   ├── common_signin_btn_icon_disabled_focus_dark.9.png
│   │   ├── common_signin_btn_icon_disabled_focus_light.9.png
│   │   ├── common_signin_btn_icon_disabled_light.9.png
│   │   ├── common_signin_btn_icon_focus_dark.9.png
│   │   ├── common_signin_btn_icon_focus_light.9.png
│   │   ├── common_signin_btn_icon_normal_dark.9.png
│   │   ├── common_signin_btn_icon_normal_light.9.png
│   │   ├── common_signin_btn_icon_pressed_dark.9.png
│   │   ├── common_signin_btn_icon_pressed_light.9.png
│   │   ├── common_signin_btn_text_disabled_dark.9.png
│   │   ├── common_signin_btn_text_disabled_focus_dark.9.png
│   │   ├── common_signin_btn_text_disabled_focus_light.9.png
│   │   ├── common_signin_btn_text_disabled_light.9.png
│   │   ├── common_signin_btn_text_focus_dark.9.png
│   │   ├── common_signin_btn_text_focus_light.9.png
│   │   ├── common_signin_btn_text_normal_dark.9.png
│   │   ├── common_signin_btn_text_normal_light.9.png
│   │   ├── common_signin_btn_text_pressed_dark.9.png
│   │   ├── common_signin_btn_text_pressed_light.9.png
│   │   ├── ic_plusone_medium_off_client.png
│   │   ├── ic_plusone_small_off_client.png
│   │   ├── ic_plusone_standard_off_client.png
│   │   ├── ic_plusone_tall_off_client.png
│   │   └── notify_panel_notification_icon_bg.png
│   ├── drawable-mdpi
│   │   ├── common_signin_btn_icon_disabled_dark.9.png
│   │   ├── common_signin_btn_icon_disabled_focus_dark.9.png
│   │   ├── common_signin_btn_icon_disabled_focus_light.9.png
│   │   ├── common_signin_btn_icon_disabled_light.9.png
│   │   ├── common_signin_btn_icon_focus_dark.9.png
│   │   ├── common_signin_btn_icon_focus_light.9.png
│   │   ├── common_signin_btn_icon_normal_dark.9.png
│   │   ├── common_signin_btn_icon_normal_light.9.png
│   │   ├── common_signin_btn_icon_pressed_dark.9.png
│   │   ├── common_signin_btn_icon_pressed_light.9.png
│   │   ├── common_signin_btn_text_disabled_dark.9.png
│   │   ├── common_signin_btn_text_disabled_focus_dark.9.png
│   │   ├── common_signin_btn_text_disabled_focus_light.9.png
│   │   ├── common_signin_btn_text_disabled_light.9.png
│   │   ├── common_signin_btn_text_focus_dark.9.png
│   │   ├── common_signin_btn_text_focus_light.9.png
│   │   ├── common_signin_btn_text_normal_dark.9.png
│   │   ├── common_signin_btn_text_normal_light.9.png
│   │   ├── common_signin_btn_text_pressed_dark.9.png
│   │   ├── common_signin_btn_text_pressed_light.9.png
│   │   ├── ic_plusone_medium_off_client.png
│   │   ├── ic_plusone_small_off_client.png
│   │   ├── ic_plusone_standard_off_client.png
│   │   ├── ic_plusone_tall_off_client.png
│   │   └── notify_panel_notification_icon_bg.png
│   ├── drawable-xhdpi
│   │   ├── common_signin_btn_icon_disabled_dark.9.png
│   │   ├── common_signin_btn_icon_disabled_focus_dark.9.png
│   │   ├── common_signin_btn_icon_disabled_focus_light.9.png
│   │   ├── common_signin_btn_icon_disabled_light.9.png
│   │   ├── common_signin_btn_icon_focus_dark.9.png
│   │   ├── common_signin_btn_icon_focus_light.9.png
│   │   ├── common_signin_btn_icon_normal_dark.9.png
│   │   ├── common_signin_btn_icon_normal_light.9.png
│   │   ├── common_signin_btn_icon_pressed_dark.9.png
│   │   ├── common_signin_btn_icon_pressed_light.9.png
│   │   ├── common_signin_btn_text_disabled_dark.9.png
│   │   ├── common_signin_btn_text_disabled_focus_dark.9.png
│   │   ├── common_signin_btn_text_disabled_focus_light.9.png
│   │   ├── common_signin_btn_text_disabled_light.9.png
│   │   ├── common_signin_btn_text_focus_dark.9.png
│   │   ├── common_signin_btn_text_focus_light.9.png
│   │   ├── common_signin_btn_text_normal_dark.9.png
│   │   ├── common_signin_btn_text_normal_light.9.png
│   │   ├── common_signin_btn_text_pressed_dark.9.png
│   │   ├── common_signin_btn_text_pressed_light.9.png
│   │   ├── ic_plusone_medium_off_client.png
│   │   ├── ic_plusone_small_off_client.png
│   │   ├── ic_plusone_standard_off_client.png
│   │   └── ic_plusone_tall_off_client.png
│   ├── drawable-xxhdpi
│   │   ├── common_signin_btn_icon_disabled_dark.9.png
│   │   ├── common_signin_btn_icon_disabled_focus_dark.9.png
│   │   ├── common_signin_btn_icon_disabled_focus_light.9.png
│   │   ├── common_signin_btn_icon_disabled_light.9.png
│   │   ├── common_signin_btn_icon_focus_dark.9.png
│   │   ├── common_signin_btn_icon_focus_light.9.png
│   │   ├── common_signin_btn_icon_normal_dark.9.png
│   │   ├── common_signin_btn_icon_normal_light.9.png
│   │   ├── common_signin_btn_icon_pressed_dark.9.png
│   │   ├── common_signin_btn_icon_pressed_light.9.png
│   │   ├── common_signin_btn_text_disabled_dark.9.png
│   │   ├── common_signin_btn_text_disabled_focus_dark.9.png
│   │   ├── common_signin_btn_text_disabled_focus_light.9.png
│   │   ├── common_signin_btn_text_disabled_light.9.png
│   │   ├── common_signin_btn_text_focus_dark.9.png
│   │   ├── common_signin_btn_text_focus_light.9.png
│   │   ├── common_signin_btn_text_normal_dark.9.png
│   │   ├── common_signin_btn_text_normal_light.9.png
│   │   ├── common_signin_btn_text_pressed_dark.9.png
│   │   ├── common_signin_btn_text_pressed_light.9.png
│   │   ├── ic_plusone_medium_off_client.png
│   │   ├── ic_plusone_small_off_client.png
│   │   ├── ic_plusone_standard_off_client.png
│   │   └── ic_plusone_tall_off_client.png
│   └── layout
│       ├── downloading_expansion.xml
│       └── status_bar_ongoing_event_progress_bar.xml
└── resources.arsc

10 directories, 122 files
```
Operating system:

openSUSE 13.2

`uname a`:
```
Linux xieshaij 3.16.7-21-debug #1 SMP Tue Apr 14 07:11:37 UTC 2015 (93c1539) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by zackp30** [comment]
Sorry for the noise, had an export template version mismatch.
