### ISSUE TITLE
Editor crash when closing any 3D scene via [x] button.

### ISSUE THREAD

**Issue by DerRidda** [okamstudio/godot#2623]
Potentially related to #2622 but seems to have different behavior.

Version:
2.0 built from git after #2617 was merged.
X11 (Linux) 64bit

Observed behavior:
When multiple scenes are opened in the editor, closing any 3D scene via the new closing button will instantly crash the editor for me. There is no additional terminal output when started via terminal.

Expected behavior:
The 3D scene will be closed without affecting the editor when clicking the close button.

Steps to reproduce:
*Open any 3D demo project that comes with multiple scenes (like "Platformer 3D" for example).
*Open several scenes.
*Click the close button [x] on any 3D scene
*Observe editor crash

**Comment by DerRidda** [comment]
After some further testing it seems like this can only be reproduced with 3D projects.

**Comment by akien-mga** [comment]
Ping @StraToN

**Comment by StraToN** [comment]
I can reproduce. Investigating. Thanks

**Comment by StraToN** [comment]
Ok, so this is a segmentation fault, here's the backtrace : 
```
(gdb) backtrace 
#0  0x00007ffff5cde848 in __dynamic_cast ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000000000079a178 in Object::cast_to<Spatial> (this=0x29e9f50)
    at core/object.h:493
#2  0x0000000000a470b2 in SpatialEditor::_request_gizmo (this=0x4dae800, 
    p_obj=0x29e9f50) at tools/editor/plugins/spatial_editor_plugin.cpp:3457
#3  0x000000000088de1c in MethodBind1<Object*>::call (this=0x4f47350, 
    p_object=0x4dae800, p_args=0x7fffffffd2e0, p_arg_count=1, r_error=...)
    at core/method_bind.inc:609
#4  0x0000000001488677 in Object::call (this=0x4dae800, p_method=..., 
    p_args=0x7fffffffd2e0, p_argcount=1, r_error=...) at core/object.cpp:895
#5  0x0000000001488179 in Object::call (this=0x4dae800, p_name=..., 
    p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at core/object.cpp:771
#6  0x000000000152d95b in MessageQueue::flush (this=0x20a3b70)
    at core/message_queue.cpp:363
#7  0x0000000000c45f07 in SceneTree::input_event (this=0x2e33150, p_event=...)
    at scene/main/scene_main_loop.cpp:437
#8  0x0000000000426fc9 in InputDefault::parse_input_event (this=0x29b9db0, 
    p_event=...) at main/input_default.cpp:219
#9  0x00000000004111dc in OS_X11::process_xevents (this=0x7fffffffd9a0)
    at platform/x11/os_x11.cpp:1289
#10 0x0000000000413469 in OS_X11::run (this=0x7fffffffd9a0)
    at platform/x11/os_x11.cpp:1949
#11 0x000000000040c6c5 in main (argc=4, argv=0x7fffffffdec8)
    at platform/x11/godot_x11.cpp:41
```

**Comment by firefly2442** [comment]
I was able to reproduce the bug (and had a couple of errors in the console):

```
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:500.
settings changed
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:500.
ERROR: set_path: Another resource is loaded from path: res://gui.scn
   At: core/resource.cpp:177.
settings changed
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:500.
```

**Comment by StraToN** [comment]
Bug potentially fixed. Please try https://github.com/StraToN/godot/commit/d64c89d44721bf2b8e84ea1a6d3c7ae0085caf6b

**Comment by akien-mga** [comment]
I confirm the fix.
